# Generated by Django 3.0.3 on 2020-02-27 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomerNumber",
            fields=[
                (
                    "number",
                    models.CharField(max_length=17, primary_key=True, serialize=False),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "mux_prefix",
                    models.CharField(db_index=True, max_length=10, unique=True),
                ),
            ],
            options={"ordering": ["created"],},
        ),
        migrations.CreateModel(
            name="TeamNumber",
            fields=[
                (
                    "number",
                    models.CharField(max_length=17, primary_key=True, serialize=False),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={"ordering": ["created"],},
        ),
        migrations.CreateModel(
            name="TelnyxMessagingProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_id", models.CharField(blank=True, max_length=40)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("intermediate_tn", models.CharField(max_length=17)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("in", "Inbound (Customer to Team)"),
                            ("out", "Outbound (Team to Customer)"),
                        ],
                        max_length=4,
                    ),
                ),
                ("teammate_tn", models.CharField(max_length=17)),
                ("customer_tn", models.CharField(max_length=17)),
                ("text", models.TextField()),
                ("delivery_status", models.CharField(max_length=20)),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="smsfwd.CustomerNumber",
                    ),
                ),
                (
                    "teammate",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="smsfwd.TeamNumber",
                    ),
                ),
            ],
            options={"ordering": ["created"],},
        ),
        migrations.AddField(
            model_name="customernumber",
            name="teammate",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="smsfwd.TeamNumber",
            ),
        ),
    ]
